name: think_launcher
description: A minimalist launcher for E-Ink screens
publish_to: 'none'
version: 1.13.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  installed_apps: ^1.0.0
  shared_preferences: ^2.2.2
  intl: ^0.20.2
  cupertino_icons: ^1.0.2
  reorderable_grid_view: ^2.2.6
  battery_plus: ^5.0.3
  notification_listener_service: ^0.3.4
  http: ^1.2.1
  geolocator: ^11.0.0
  android_intent_plus: ^5.3.0
  image_picker: ^1.1.2
  palette_generator: ^0.3.3+3
  path_provider: ^2.1.4
  file_picker: ^8.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true
